<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rp256 jt_globalSearch</name>
   <tag></tag>
   <elementGuidId>87327a4e-bf81-468d-8ad9-40379e278b4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#globalSearch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='globalSearch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>50d1a9a4-408a-446d-a3d3-b85afee7829b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0d9131a2-b539-4854-97e4-2d261a672d38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>globalSearch</value>
      <webElementGuid>7b569a4f-7573-4c09-8f1e-2b8aa2313e44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search by job title, company, &amp; skills</value>
      <webElementGuid>1502d972-69bd-44e5-ad30-9a719a172b71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input</value>
      <webElementGuid>f6fa73a7-ba69-4aed-b56d-eb16af6faaa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b3051db6-9b86-4961-b650-46b51ca2f194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Front End Engineer</value>
      <webElementGuid>679a6f2b-159e-4004-8c6a-f89d4503c934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;globalSearch&quot;)</value>
      <webElementGuid>79794c42-faf2-4561-b71f-5fb634b381a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='globalSearch']</value>
      <webElementGuid>b236d400-5342-44d6-bc02-73210e0fece4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header-navbar']/div/div[2]/div/div/form/input</value>
      <webElementGuid>f190c79f-f890-4e90-9dd3-66799d565acc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>6af3e91d-96e7-4314-b284-40c41349400e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'globalSearch' and @placeholder = 'Search by job title, company, &amp; skills' and @type = 'text']</value>
      <webElementGuid>3c47a4a2-1ac6-4c44-a945-a9659320afb6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
