<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rp256 jt_globalSearch</name>
   <tag></tag>
   <elementGuidId>bb97bc2a-cf88-4f17-9247-b6f7a529f2e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#globalSearch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='globalSearch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e8571ee6-d81e-414a-9ca3-aa7d97dc8a24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5d1d4844-74cd-4308-95b7-98c0b4b0812f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>globalSearch</value>
      <webElementGuid>31e6d9ae-3b8f-4078-a48e-fef6d0e9579c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search by job title, company, &amp; skills</value>
      <webElementGuid>e6e63250-f559-4461-8e8d-891687d32d00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input</value>
      <webElementGuid>f2e03c30-4628-4a72-ad20-a7fcc991ad73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dc47f810-69f6-415a-9846-2018cb899bee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Q</value>
      <webElementGuid>8dd3cb6c-f16b-46ab-b914-20ca1b3a0b29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;globalSearch&quot;)</value>
      <webElementGuid>2cb9b16e-ceeb-47c6-91c4-de38718e35b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='globalSearch']</value>
      <webElementGuid>85273f50-5e0b-498d-8c34-4e56574ef248</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header-navbar']/div/div[2]/div/div/form/input</value>
      <webElementGuid>23d11462-e458-42ed-9b72-38038bc17dce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>821006a9-9ed6-4bae-9bd4-5a94d8703dea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'globalSearch' and @placeholder = 'Search by job title, company, &amp; skills' and @type = 'text']</value>
      <webElementGuid>b08d8789-5083-4f4c-9123-f743ca3ba4a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
