<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rp256 jt_globalSearch</name>
   <tag></tag>
   <elementGuidId>ec9d3408-5934-47e4-ad83-827df5afc058</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#globalSearch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='globalSearch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>72c6629e-410c-490d-9c96-2b22aa477007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6efdcc51-bce1-4c90-af09-5c36f8927c06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>globalSearch</value>
      <webElementGuid>386b4bc4-3f98-4307-aa6d-71fdb2c0665d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search by job title, company, &amp; skills</value>
      <webElementGuid>9d1c48d6-f263-4dc1-9b94-1d75f840a970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input</value>
      <webElementGuid>ea7516be-204d-4f0e-8ed5-cac81592d8a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a480509d-324b-4247-b5d8-fff66a6a1fcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>S</value>
      <webElementGuid>ac046327-6c7f-4161-a4d6-123527c55a92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;globalSearch&quot;)</value>
      <webElementGuid>aec60f66-30b8-4125-8b71-0a6573ba72ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='globalSearch']</value>
      <webElementGuid>eabd49dd-ed81-493f-ad1b-fea9b8f7d965</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header-navbar']/div/div[2]/div/div/form/input</value>
      <webElementGuid>bcfbf39c-76a7-4c69-9da3-0361e7be5312</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>65e52aad-4abd-4891-85d1-758be9b3b95f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'globalSearch' and @placeholder = 'Search by job title, company, &amp; skills' and @type = 'text']</value>
      <webElementGuid>16d0325c-b21f-4117-b70f-35cc5995a69c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
