<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rp256 jt_globalSearch</name>
   <tag></tag>
   <elementGuidId>0fc7b781-8ae4-46c1-b84b-486286a722e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#globalSearch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='globalSearch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>60dc9165-f255-4ea9-9e5d-c3835b9c16bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e913638f-9277-4c6e-8cca-b36dae7b7d57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>globalSearch</value>
      <webElementGuid>2c46144e-dae3-444a-9df6-2172441b9e5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search by job title, company, &amp; skills</value>
      <webElementGuid>0f403e85-bddf-4422-b3d8-e316924e2637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input</value>
      <webElementGuid>35a18f90-a362-40fa-b962-80ceb7540d50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b1259497-6cff-40db-a1b3-9c4ba559edbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;globalSearch&quot;)</value>
      <webElementGuid>38a2cd55-9413-429b-a1b4-7f822abd341f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='globalSearch']</value>
      <webElementGuid>4fbdf61b-d538-460b-9f13-7f62d469e1f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header-navbar']/div/div[2]/div/div/form/input</value>
      <webElementGuid>57f175ce-c3a4-42c8-bdf6-377cdc3ea6a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>51c9c6eb-726a-4736-aea1-4362e6a6e919</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'globalSearch' and @placeholder = 'Search by job title, company, &amp; skills' and @type = 'text']</value>
      <webElementGuid>dbd513ce-62d9-43be-9cb6-2e6116685ced</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
